# Generated by Django 4.1.3 on 2022-11-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_prices_type_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='format',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='operation',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.FloatField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='save_type',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
