# Generated by Django 4.1.3 on 2022-11-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_prices_type_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='session',
            name='format',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='save_type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
