# Generated by Django 4.1.3 on 2022-11-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_session', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('operation', models.CharField(default=None, max_length=20, null=True)),
                ('format', models.CharField(default=None, max_length=20, null=True)),
                ('save_type', models.CharField(default=None, max_length=20, null=True)),
                ('price', models.FloatField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaveTypeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ScanFormat',
        ),
        migrations.DeleteModel(
            name='ScanSaveType',
        ),
        migrations.DeleteModel(
            name='ScanType',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
