# Generated by Django 4.1.3 on 2022-11-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_session_date_time_session_format_session_save_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
