# Generated by Django 4.1.3 on 2022-11-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_session_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='format',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='save_type',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
