# Generated by Django 4.1.3 on 2022-11-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_session_date_time_alter_session_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='operation',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
